---
resource_types:
- name: slack-notification-resource
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: Thursday_at_3pm
  type: time
  icon: clock-outline
  source:
    start: '3PM'
    stop: '3:30 PM'
    interval: 1h
    location: America/New_York
    days:
    - Thursday

- name: notifier
  type: slack-notification-resource
  source:
    url: ((slack-notification-url))
jobs:
- name: notify
  plan:
  - get: Thursday_at_3pm
    trigger: true
  - task: notify-standup-host
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      outputs:
      - name: slack-message

      run:
        path: /bin/sh
        args:
        - -exc
        - |
          wget -q -O- ((standup-app-url))/slack_notification/ > slack-message/announcement.txt
  - put: notifier
    params:
      text_file: slack-message/announcement.txt

